@echo off
REM v3.6 commit - root cause fix (v1 base + LRU TTL)
chcp 65001 >nul
cd /d "%~dp0"

if exist ".git\index.lock" del /F /Q ".git\index.lock"

(
echo v3.6: root cause - v1 base preserves fixes; LRU TTL prevents stale Yahoo cache
echo.
echo Why v3.5 fixes kept regressing:
echo.
echo Problem A: stock_terminal_v2.html is auto-generated by build_v2.py
echo            from stock_terminal.html v1 base. All v3.5 loadSym /
echo            renderChart fixes were written to v2.html and got wiped
echo            every time start_terminal_v2.bat re-ran the build.
echo            User saw "fixed once, then jumps back" pattern.
echo            Fix: move all loadSym + renderChart edits to v1 base.
echo.
echo Problem B: server.py LRUCache had NO TTL ^(comment even said so^).
echo            If server's first Yahoo call hit a query1/query2 desync
echo            window ^(common in post-market hours^), the entire stale
echo            response ^(rmp, rmt, candles all from yesterday^) got cached
echo            forever. Every loadSym afterwards hit cache and got the
echo            stale snapshot - even the rmt-vs-last.t alignment check
echo            failed because BOTH were stale together.
echo            wl_live_v3.js uses nocache=1 so its poll was fine, hence
echo            "chip correct, click shows yesterday" random-feeling bug.
echo            Fix: LRUCache now takes ttl_seconds=60. Stale entries
echo            expire automatically; 60s window matches chip poll cadence.
echo.
echo Files:
echo   stock_terminal.html   loadSym: synthetic today-K + yesterdayClose;
echo                         renderChart: user-local TZ shift + getUTC*
echo                         crosshair read-back; SMA/BB/Volume shifted.
echo   server.py             LRUCache with TTL=60s for all entries.
echo   plan_v3.js            inject CSS for form: box-sizing + min-width:0
echo                         + hide spinner arrows so buy zone inputs no
echo                         longer overflow the 340px right panel.
echo   rebuild_and_restart.bat  one-shot: python build_v2.py + kill+restart.
echo   README.md             new v3.6 section explaining root cause.
) > .git\COMMIT_MSG_v36.txt

git add README.md server.py stock_terminal.html plan_v3.js rebuild_and_restart.bat
git diff --cached --name-only
echo.

git commit -F .git\COMMIT_MSG_v36.txt
del /F /Q .git\COMMIT_MSG_v36.txt

echo.
git log --oneline -5
pause
