@echo off
REM Combined commit: v3.6 (root cause) + v3.7 (global ETF holdings)
chcp 65001 >nul
cd /d "%~dp0"

if exist ".git\index.lock" del /F /Q ".git\index.lock"

(
echo v3.6 + v3.7: root cause stale-price fix + global ETF holdings
echo.
echo ============================================================
echo  v3.6: why v3.5 fixes kept regressing
echo ============================================================
echo.
echo Problem A: stock_terminal_v2.html is auto-generated by build_v2.py
echo            from stock_terminal.html v1 base. All v3.5 loadSym /
echo            renderChart fixes were written to v2.html and got wiped
echo            every time start_terminal_v2.bat re-ran the build.
echo            User saw "fixed once, then jumps back" pattern.
echo            Fix: move all loadSym + renderChart edits to v1 base.
echo.
echo Problem B: server.py LRUCache had NO TTL ^(comment even said so^).
echo            If server's first Yahoo call hit a query1/query2 desync
echo            window ^(common in post-market hours^), the entire stale
echo            response ^(rmp, rmt, candles all from yesterday^) got cached
echo            forever. Every loadSym afterwards hit cache and got the
echo            stale snapshot - even the rmt-vs-last.t alignment check
echo            failed because BOTH were stale together.
echo            wl_live_v3.js uses nocache=1 so its poll was fine, hence
echo            "chip correct, click shows yesterday" random-feeling bug.
echo            Fix: LRUCache now takes ttl_seconds=60. Stale entries
echo            expire automatically; 60s window matches chip poll cadence.
echo.
echo Problem C: PLAN form buy-zone inputs overflow the 340px right panel.
echo            type=number spinner arrows enforce intrinsic min-width
echo            on flex:1 inputs - "38" upper bound cut off screen.
echo            Fix: plan_v3.js injects CSS at boot - box-sizing,
echo            min-width:0, and hides webkit/moz spinner arrows.
echo.
echo v3.6 files:
echo   stock_terminal.html   loadSym: synthetic today-K + yesterdayClose;
echo                         renderChart: user-local TZ shift + getUTC*
echo                         crosshair read-back; SMA/BB/Volume shifted.
echo   server.py             LRUCache with TTL=60s for all entries.
echo   plan_v3.js            inject CSS: box-sizing + min-width:0 + hide
echo                         spinner arrows so buy zone inputs fit.
echo   rebuild_and_restart.bat  one-shot: python build_v2.py + kill+restart.
echo.
echo ============================================================
echo  v3.7: global ETF holdings + multi-market chart click-through
echo ============================================================
echo.
echo Problem: 00988A ^(Uni-President Global Innovation Active^) showed
echo   only 13 Taiwan stocks in TOP 10 holdings even though it's a
echo   global ETF with 46 holdings spanning US ^(17^) / TW ^(13^) / JP ^(9^)
echo   / KR ^(1^) / CN ^(1^). The TOP 3 by weight ^(Samsung, Micron, AMD^)
echo   all missing - users saw misleading "all-TW" composition.
echo.
echo Root cause: etf_delta_tracker.py _MDJ_ROW_RE hardcoded:
echo   1^) ^(\d{4,6}^) accepts pure digits only - AMD/MU/AAPL filtered
echo   2^) \.TW suffix locked - 6963.JP/009150.KS/0700.HK filtered
echo   41/46 foreign holdings of 00988A excluded by regex.
echo.
echo Fix:
echo   etf_delta_tracker.py:
echo     - Regex relaxed: code = [0-9A-Za-z]{1,7}; suffix = [A-Z]{2}
echo     - holdings now carry 'market' field
echo       ^(TW/US/JP/KS/HK/SH/SZ/DE/L^)
echo     - dedupe key bumped to code.market ^(was just code^).
echo   etf_v3.js:
echo     - new mapToYahoo^(sym, mdjMkt^): MoneyDJ market code to Yahoo
echo       symbol suffix. JP-^>.T, SH-^>.SS, HK auto-padStart^(4,'0'^);
echo       passes uiMkt='US' so loadSym doesn't re-suffix with .TW.
echo     - click handler reads data-mkt and routes via mapToYahoo.
echo     - display shows .US/.JP/.KS labels next to foreign codes;
echo       TW stays clean ^(no suffix shown^).
echo.
echo Verified all 6 markets via Chrome -^> localhost:18432/yf/...:
echo   6963.T    -^> ROHM CO LTD       ^(JPY 5458^)
echo   009150.KS -^> SamsungElecMech   ^(KRW 2127000^)
echo   AMD       -^> AMD               ^(USD 516.10^)
echo   0700.HK   -^> TENCENT           ^(HKD 427.20^)
echo   600519.SS -^> KWEICHOW MOUTAI   ^(CNY 1326^)
echo   2454.TW   -^> MediaTek          ^(TWD 4310^)
echo.
echo v3.7 files:
echo   etf_delta_tracker.py  regex + market field in 2 fetch functions
echo   etf_v3.js             mapToYahoo + click handler + suffix labels
echo.
echo ============================================================
echo  Apply order after pulling this commit:
echo ============================================================
echo   1. rebuild_and_restart.bat        ^(v3.6 + v3.7 client+server^)
echo   2. python etf_delta_tracker.py    ^(re-fetch holdings w/ market^)
echo.
echo README.md updated with v3.6 + v3.7 sections explaining both fixes.
) > .git\COMMIT_MSG_v36_37.txt

REM Stage all changed files from both releases
git add README.md ^
        server.py ^
        stock_terminal.html ^
        plan_v3.js ^
        etf_delta_tracker.py ^
        etf_v3.js ^
        rebuild_and_restart.bat

echo === Staged files ^(7 expected^): ===
git diff --cached --name-only
echo.

git commit -F .git\COMMIT_MSG_v36_37.txt
del /F /Q .git\COMMIT_MSG_v36_37.txt

echo.
echo === Last 5 commits: ===
git log --oneline -5
pause
