'use strict';
const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const root=path.resolve(__dirname,'..');const dataCode=fs.readFileSync(path.join(root,'src/core/decision_data_v5.js'),'utf8');const uiCode=fs.readFileSync(path.join(root,'src/ui/decision_v5.js'),'utf8');const kernelCode=fs.readFileSync(path.join(root,'src/core/app_kernel_v5.js'),'utf8');
function context(asOf='old'){return {ok:true,asOf,regime:{id:'NARROW_RALLY'},actionEnvelope:{},keyLevels:{}}}
function response(status,body){return {ok:status===200,status,text:async()=>typeof body==='string'?body:JSON.stringify(body)}}
function environment(fetch){const store={};const traces=[];const w={SERVER:'http://fixture',dispatchEvent(){},FeatureFlags:{isEnabled:()=>false}};const sandbox={window:w,FeatureFlags:w.FeatureFlags,location:{origin:'http://fixture'},fetch,AbortController,CustomEvent:class{},localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=v},console,Date,Promise,setTimeout,clearTimeout};vm.createContext(sandbox);vm.runInContext(dataCode,sandbox);sandbox.DecisionData=w.DecisionData;sandbox.DecisionData.publish(context(),'fixture');return {sandbox,w,trace:()=>JSON.parse(store.st_decision_ui_trace_v1||'[]')}}
function attachUi(env){const s=env.sandbox;let busy=false;let shown=null;const deadlines=[];const body={innerHTML:''};Object.assign(s,{marketRefreshInflight:null,lastMarketRefreshAt:0,lastContext:context(),lastHoldings:[],portfolioMode:'actual',SRV:'http://fixture',ensureMount:()=>body,nextCorrelationId:()=> 'focused-refresh',trace:(e,id,d)=>env.w.DecisionData.trace(e,id,d),setRefreshState:b=>{busy=b},holdingsFromWatch:()=>[],holdingsFromPositions:()=>[],render:c=>{s.lastContext=c},showEmpty:(message,detail)=>{shown={message,detail}},setTimeout:fn=>{deadlines.push(fn);return deadlines.length},clearTimeout:()=>{}});const start=uiCode.indexOf('  function refreshMarketData(');const end=uiCode.indexOf('  function holdingsFromPositions(',start);vm.runInContext(uiCode.slice(start,end),s);return {refresh:()=>s.refreshMarketData(),busy:()=>busy,shown:()=>shown,expire:()=>deadlines[0]()}}
async function run(){let count=0;async function test(name,fn){await fn();count++;console.log('PASS '+name)}
await test('strict context HTTP failure cannot return cached success; retry succeeds',async()=>{let fail=true;const e=environment(async()=>response(fail?503:200,fail?{ok:false}:context('new')));await assert.rejects(e.w.DecisionData.refresh({strict:true,force:true}),/HTTP 503/);assert.equal(e.w.DecisionData.get().context.asOf,'old');fail=false;assert.equal((await e.w.DecisionData.refresh({strict:true,force:true})).context.asOf,'new')});
await test('strict invalid JSON rejects',async()=>{const e=environment(async()=>response(200,'invalid'));await assert.rejects(e.w.DecisionData.refresh({strict:true}),/JSON invalid/)});
await test('strict ok:false payload with regime is rejected',async()=>{const e=environment(async()=>response(200,{...context(),ok:false}));await assert.rejects(e.w.DecisionData.refresh({strict:true}),/unavailable/)});
await test('strict missing regime is rejected',async()=>{const e=environment(async()=>response(200,{ok:true}));await assert.rejects(e.w.DecisionData.refresh({strict:true}),/unavailable/)});
await test('legacy background reader preserves last-good context',async()=>{const e=environment(async()=>response(503,{ok:false}));assert.equal((await e.w.DecisionData.refresh()).context.asOf,'old')});
await test('real UI chain logs failure for context 503 and restores button; retry logs success',async()=>{let fail=true;const e=environment(async url=>url.includes('/pulse')?response(200,{ok:true}):response(fail?503:200,fail?{ok:false}:context('new')));const ui=attachUi(e);assert.equal(await ui.refresh(),null);assert.match(ui.shown().detail,/HTTP 503/);assert.equal(ui.busy(),false);assert.equal(e.trace().filter(t=>t.event==='market_refresh_terminal_success').length,0);fail=false;assert.equal((await ui.refresh()).asOf,'new');assert.equal(e.trace().filter(t=>t.event==='market_refresh_terminal_success').length,1)});
await test('real UI common deadline aborts pending context and permits retry',async()=>{let fail=true;const e=environment(async(url,opts)=>{if(url.includes('/pulse'))return response(200,{ok:true});if(!fail)return response(200,context('retry'));return new Promise((resolve,reject)=>{opts.signal.addEventListener('abort',()=>reject(Object.assign(new Error('aborted'),{name:'AbortError'})),{once:true})})});const ui=attachUi(e);const p=ui.refresh();for(let i=0;i<8;i++)await Promise.resolve();ui.expire();assert.equal(await p,null);assert.equal(ui.busy(),false);assert.match(ui.shown().detail,/aborted/);fail=false;assert.equal((await ui.refresh()).asOf,'retry')});
await test('API kernel respects caller abort rather than replacing its signal',async()=>{const e=environment((url,opts)=>new Promise((resolve,reject)=>{if(opts.signal.aborted)return reject(Object.assign(new Error('aborted'),{name:'AbortError'}));opts.signal.addEventListener('abort',()=>reject(Object.assign(new Error('aborted'),{name:'AbortError'})),{once:true})}));vm.runInContext(kernelCode,e.sandbox);const controller=new AbortController();const p=e.w.AppKernel.api.request('/pulse?refresh=1',{signal:controller.signal,timeoutMs:20000});controller.abort();await assert.rejects(p,{name:'AbortError'});const pre=new AbortController();pre.abort();await assert.rejects(e.w.AppKernel.api.request('/pulse?refresh=1',{signal:pre.signal}),{name:'AbortError'})});
console.log(`${count} focused refresh behavioral tests passed`)}
run().catch(e=>{console.error(e);process.exitCode=1});
