'use strict';
const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const root=path.resolve(__dirname,'..');const dataCode=fs.readFileSync(path.join(root,'src/core/decision_data_v5.js'),'utf8');const uiCode=fs.readFileSync(path.join(root,'src/ui/decision_v5.js'),'utf8');const kernelCode=fs.readFileSync(path.join(root,'src/core/app_kernel_v5.js'),'utf8');
function context(asOf='old'){return {ok:true,asOf,regime:{id:'NARROW_RALLY'},actionEnvelope:{},keyLevels:{}}}
function response(status,body){return {ok:status===200,status,text:async()=>typeof body==='string'?body:JSON.stringify(body)}}
function environment(fetch){const store={};const traces=[];const w={SERVER:'http://fixture',dispatchEvent(){},FeatureFlags:{isEnabled:()=>false}};const sandbox={window:w,FeatureFlags:w.FeatureFlags,location:{origin:'http://fixture'},fetch,AbortController,AbortSignal,CustomEvent:class{},localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=v},console,Date,Promise,setTimeout,clearTimeout};vm.createContext(sandbox);vm.runInContext(dataCode,sandbox);sandbox.DecisionData=w.DecisionData;sandbox.DecisionData.publish(context(),'fixture');return {sandbox,w,trace:()=>JSON.parse(store.st_decision_ui_trace_v1||'[]')}}
function attachUi(env){const s=env.sandbox;let busy=false;let shown=null;const deadlines=[];const body={innerHTML:''};Object.assign(s,{lifecycleSequence:0,marketRefreshController:null,marketRefreshBackground:false,portfolioRequestKey:'fixture',portfolioStillCurrent:()=>true,portfolioRequestOptions:()=>({portfolioInputKey:'fixture'}),discardChangedPortfolio:()=>{},canUpdateMarket:()=>true,marketUpdateStatus:detail=>{shown={detail}},marketRefreshInflight:null,lastMarketRefreshAt:0,lastContext:context(),lastHoldings:[],portfolioMode:'actual',SRV:'http://fixture',ensureMount:()=>body,nextCorrelationId:()=> 'focused-refresh',trace:(e,id,d)=>env.w.DecisionData.trace(e,id,d),setRefreshState:b=>{busy=b},holdingsFromWatch:()=>[],holdingsFromPositions:()=>[],render:c=>{s.lastContext=c},showEmpty:(message,detail)=>{shown={message,detail}},setTimeout:fn=>{deadlines.push(fn);return deadlines.length},clearTimeout:()=>{}});env.w.DecisionData.refreshPulse=async options=>({pulse:JSON.parse(await (await s.fetch('http://fixture/pulse?refresh=1',{signal:options.signal})).text()),job:null,error:null});const start=uiCode.indexOf('  function refreshMarketData(');const end=uiCode.indexOf('  function portfolioInput(',start);assert.ok(start>=0 && end>start,'refreshMarketData fixture anchors missing');vm.runInContext(uiCode.slice(start,end),s);return {refresh:()=>s.refreshMarketData(),busy:()=>busy,shown:()=>shown,expire:()=>deadlines[0]()}}
async function run(){let count=0;async function test(name,fn){await fn();count++;console.log('PASS '+name)}
await test('strict context HTTP failure cannot return cached success; retry succeeds',async()=>{let fail=true;const e=environment(async()=>response(fail?503:200,fail?{ok:false}:context('new')));await assert.rejects(e.w.DecisionData.refresh({strict:true,force:true}),/HTTP 503/);assert.equal(e.w.DecisionData.get().context.asOf,'old');fail=false;assert.equal((await e.w.DecisionData.refresh({strict:true,force:true})).context.asOf,'new')});
await test('strict invalid JSON rejects',async()=>{const e=environment(async()=>response(200,'invalid'));await assert.rejects(e.w.DecisionData.refresh({strict:true}),/JSON invalid/)});
await test('strict ok:false payload with regime is rejected',async()=>{const e=environment(async()=>response(200,{...context(),ok:false}));await assert.rejects(e.w.DecisionData.refresh({strict:true}),/unavailable/)});
await test('strict missing regime is rejected',async()=>{const e=environment(async()=>response(200,{ok:true}));await assert.rejects(e.w.DecisionData.refresh({strict:true}),/unavailable/)});
await test('legacy background reader preserves last-good context',async()=>{const e=environment(async()=>response(503,{ok:false}));assert.equal((await e.w.DecisionData.refresh()).context.asOf,'old')});
await test('real UI chain logs failure for context 503 and restores button; retry logs success',async()=>{let fail=true;const e=environment(async url=>url.includes('/pulse')?response(200,{ok:true}):response(fail?503:200,fail?{ok:false}:context('new')));const ui=attachUi(e);assert.equal(await ui.refresh(),null);assert.match(ui.shown().detail,/HTTP 503/);assert.equal(ui.busy(),false);assert.equal(e.trace().filter(t=>t.event==='market_refresh_terminal_success').length,0);fail=false;assert.equal((await ui.refresh()).asOf,'new');assert.equal(e.trace().filter(t=>t.event==='market_refresh_terminal_success').length,1)});
await test('real UI common deadline aborts pending context and permits retry',async()=>{let fail=true;const e=environment(async(url,opts)=>{if(url.includes('/pulse'))return response(200,{ok:true});if(!fail)return response(200,context('retry'));return new Promise((resolve,reject)=>{opts.signal.addEventListener('abort',()=>reject(Object.assign(new Error('aborted'),{name:'AbortError'})),{once:true})})});const ui=attachUi(e);const p=ui.refresh();for(let i=0;i<8;i++)await Promise.resolve();ui.expire();assert.equal(await p,null);assert.equal(ui.busy(),false);assert.match(ui.shown().detail,/aborted|逾時/);fail=false;assert.equal((await ui.refresh()).asOf,'retry')});
await test('API kernel respects caller abort rather than replacing its signal',async()=>{const e=environment((url,opts)=>new Promise((resolve,reject)=>{if(opts.signal.aborted)return reject(Object.assign(new Error('aborted'),{name:'AbortError'}));opts.signal.addEventListener('abort',()=>reject(Object.assign(new Error('aborted'),{name:'AbortError'})),{once:true})}));vm.runInContext(kernelCode,e.sandbox);const controller=new AbortController();const p=e.w.AppKernel.api.request('/pulse?refresh=1',{signal:controller.signal,timeoutMs:20000});controller.abort();await assert.rejects(p,{name:'AbortError'});const pre=new AbortController();pre.abort();await assert.rejects(e.w.AppKernel.api.request('/pulse?refresh=1',{signal:pre.signal}),{name:'AbortError'})});
await test('common deadline cancels a Pulse body after headers have arrived',async()=>{const e=environment(async(url,opts)=>({ok:true,status:200,text:()=>new Promise((resolve,reject)=>{opts.signal.addEventListener('abort',()=>reject(Object.assign(new Error('body aborted'),{name:'AbortError'})),{once:true})}),clone(){return this}}));vm.runInContext(kernelCode,e.sandbox);const ui=attachUi(e);const p=ui.refresh();for(let i=0;i<10;i++)await Promise.resolve();ui.expire();assert.equal(await p,null);assert.equal(ui.busy(),false);assert.match(ui.shown().detail,/body aborted|逾時/)});
await test('strict caller never reuses a nonstrict in-flight fallback',async()=>{let release;let calls=0;const e=environment(async()=>{calls++;if(calls===1)return new Promise(r=>{release=()=>r(response(503,{ok:false}))});return response(503,{ok:false})});const old=e.w.DecisionData.refresh();await assert.rejects(e.w.DecisionData.refresh({strict:true}),/HTTP 503/);release();assert.equal((await old).context.asOf,'old');assert.equal(calls,2)});
await test('caller-owned request can abort while an existing shared request stays valid',async()=>{let release;let calls=0;const e=environment((url,opts)=>{calls++;if(calls===1)return new Promise(r=>{release=()=>r({ok:true,clone(){return this}})});return new Promise((resolve,reject)=>{opts.signal.addEventListener('abort',()=>reject(Object.assign(new Error('aborted'),{name:'AbortError'})),{once:true})})});vm.runInContext(kernelCode,e.sandbox);const first=e.w.AppKernel.api.request('/pulse?refresh=1');const controller=new AbortController();const second=e.w.AppKernel.api.request('/pulse?refresh=1',{signal:controller.signal});controller.abort();await assert.rejects(second,{name:'AbortError'});release();assert.equal((await first).ok,true);assert.equal(calls,2)});
await test('nonstrict caller never inherits strict in-flight rejection',async()=>{let release;let calls=0;const e=environment(async()=>{calls++;if(calls===1)return new Promise(r=>{release=()=>r(response(503,{ok:false}))});return response(503,{ok:false})});const strict=e.w.DecisionData.refresh({strict:true});const rejection=assert.rejects(strict,/HTTP 503/);assert.equal((await e.w.DecisionData.refresh()).context.asOf,'old');release();await rejection;assert.equal(calls,2)});
await test('common deadline cancels context body after its headers and permits retry',async()=>{let fail=true;let bodyStarted=false;const e=environment(async(url,opts)=>{if(url.includes('/pulse'))return response(200,{ok:true});if(!fail)return response(200,context('retry'));return {ok:true,status:200,text:()=>{bodyStarted=true;return new Promise((resolve,reject)=>opts.signal.addEventListener('abort',()=>reject(Object.assign(new Error('context body aborted'),{name:'AbortError'})),{once:true}))}}});const ui=attachUi(e);const p=ui.refresh();for(let i=0;i<25&&!bodyStarted;i++)await Promise.resolve();assert.equal(bodyStarted,true);ui.expire();assert.equal(await p,null);assert.equal(ui.busy(),false);assert.match(ui.shown().detail,/context body aborted|逾時/);assert.equal(e.w.DecisionData.get().context.asOf,'old');fail=false;assert.equal((await ui.refresh()).asOf,'retry')});
await test('kernel timeout detaches caller bridge when AbortSignal.any is unavailable',async()=>{let expire;let added=0;let removed=0;const caller=new AbortController();const add=caller.signal.addEventListener.bind(caller.signal);const remove=caller.signal.removeEventListener.bind(caller.signal);caller.signal.addEventListener=(...args)=>{added++;return add(...args)};caller.signal.removeEventListener=(...args)=>{removed++;return remove(...args)};const e=environment((url,opts)=>new Promise((resolve,reject)=>opts.signal.addEventListener('abort',()=>reject(Object.assign(new Error('kernel timeout'),{name:'AbortError'})),{once:true})));e.sandbox.AbortSignal={};e.sandbox.setTimeout=fn=>{expire=fn;return 1};e.sandbox.clearTimeout=()=>{};vm.runInContext(kernelCode,e.sandbox);const p=e.w.AppKernel.api.request('/pulse?refresh=1',{signal:caller.signal,timeoutMs:250});assert.equal(added,1);expire();await assert.rejects(p,{name:'AbortError'});assert.equal(removed,1);assert.equal(caller.signal.aborted,false)});
console.log(`${count} focused refresh behavioral tests passed`)}
run().catch(e=>{console.error(e);process.exitCode=1});
